"""Added number of ratings column to movies table

Revision ID: 2be9c5b847f4
Revises: f9c5e360ab8f
Create Date: 2025-06-29 21:27:39.502036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be9c5b847f4'
down_revision: Union[str, None] = 'f9c5e360ab8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('number_of_ratings', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.alter_column('ratings', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=3, scale=1),
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('ratings', 'rating',
               existing_type=sa.Numeric(precision=3, scale=1),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('movies', 'number_of_ratings')
    # ### end Alembic commands ###
