[mypy]
# Be strict inside the package
strict = True

# Allow missing stubs for some third-party packages used at runtime
ignore_missing_imports = True

[mypy-tests.*]
ignore_errors = True

[mypy-alembic.*]
ignore_errors = True
